config/routes.rb
Rails.application.routes.draw do
  resources :posts do
  	collection do
  		get '/search'=>'posts#search'
  	end
  end

  devise_for :users
  resources :snippet_uploads
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'snippet_uploads#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :snippet_upload
end

app/models/snippet_upload.rb
class SnippetUpload < ApplicationRecord
	validates_presence_of :title

	has_many_attached :files

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :snippet_upload 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/posts_controller.rb
require "rexml/document"
include REXML 

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search

    begin

      content = '<?xml version="1.0" encoding="utf-8"?>
        <CodeSnippets>
          <CodeSnippet Format="1.0.0">
            <Header>
              <Title>stepsByAutoId</Title>
              <Shortcut>stepsByAutoId</Shortcut>
              <Description />
              <Author />
              <SnippetTypes>
                <SnippetType>Expansion</SnippetType>
              </SnippetTypes>
            </Header>
            <Snippet>
              <Declarations />
              <Code Language="sql"><![CDATA[SELECT   fwfs.AutoId,''EXEC dbo.PS_Workflow_DWFSAutoId '' + CAST(fwfs.AutoId AS NVARCHAR(MAX)),tc.AutoId,fwi.AutoId,fwfd.Name,fwfsd.ControllerClass, fwfsd.Name,fwfsd.CaptionTr,fwfs.CreateUserTime FROM FWFStep fwfs 
        JOIN dbo.FWFStepDef fwfsd WITH (NOLOCK) ON fwfs.WFStepDefId = fwfsd.ID
        JOIN dbo.FWFInstance fwi WITH (NOLOCK) ON fwi.ID = fwfs.WFInstanceId
        JOIN dbo.FWFDefinition fwfd WITH (NOLOCK) ON fwfd.ID = fwfsd.WFDefinitionId
        JOIN dbo.TProductInstanceBase tpib WITH (NOLOCK) ON tpib.ID = fwi.RecID
        JOIN dbo.TContractDetail tcd WITH (NOLOCK) ON tcd.ID = tpib.ContractDetailId
        JOIN dbo.TCustomer tc WITH (NOLOCK) ON tc.ID = tcd.CustomerId
        WHERE 
        --fwfs.AutoId = 344624150
        fwi.AutoId = 40791481 
        AND fwfs.GcRecordId IS NULL ORDER BY fwfs.AutoId]]></Code>
            </Snippet>
          </CodeSnippet>
        </CodeSnippets>'
    
      doc = Document.new content

      title = XPath.first(doc, "//CodeSnippets/CodeSnippet/Header/Title").text

      s = XPath.first(doc, "//CodeSnippets/CodeSnippet/Snippet/Code").text

      respond_to do |format|
        format.html { redirect_to posts_url, notice: s.to_s }
        format.json { head :no_content }
      end
    

    rescue StandardError => msg
      format.html { render :show }
      format.json { render json: msg, status: :unprocessable_entity }
    end
                  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :snippet_upload_id)
    end
end

app/controllers/snippet_uploads_controller.rb
require "rexml/document"
include REXML 


class SnippetUploadsController < ApplicationController

  before_action :authenticate_user!

  before_action :set_snippet_upload, only: [:show, :edit, :update, :destroy]

  # GET /snippet_uploads
  # GET /snippet_uploads.json
  def index
    @snippet_uploads = SnippetUpload.all
  end

  # GET /snippet_uploads/1
  # GET /snippet_uploads/1.json
  def show
  end

  # GET /snippet_uploads/new
  def new
    @snippet_upload = SnippetUpload.new
  end

  # GET /snippet_uploads/1/edit
  def edit
  end

  # POST /snippet_uploads
  # POST /snippet_uploads.json
  def create
    @snippet_upload = SnippetUpload.new(snippet_upload_params)

    @snippet_upload.user = current_user

    respond_to do |format|
      if @snippet_upload.save
        @snippet_upload.files.each do |file|
          upload_to_snippet(file,current_user,@snippet_upload)
        end

        format.html { redirect_to @snippet_upload, notice: 'Snippet upload was successfully created.' }
        format.json { render :show, status: :created, location: @snippet_upload }
      else
        format.html { render :new }
        format.json { render json: @snippet_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippet_uploads/1
  # PATCH/PUT /snippet_uploads/1.json
  def update
    respond_to do |format|
      if @snippet_upload.update(snippet_upload_params)
        format.html { redirect_to @snippet_upload, notice: 'Snippet upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet_upload }
      else
        format.html { render :edit }
        format.json { render json: @snippet_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippet_uploads/1
  # DELETE /snippet_uploads/1.json
  def destroy

    @snippet_upload.destroy
    respond_to do |format|
      format.html { redirect_to snippet_uploads_url, notice: 'Snippet upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload_to_snippet(file,user,snippet_upload)
    content = file.download
    content_s =  content.bytes.pack("c*").force_encoding("UTF-8") 
    if file.filename.to_s.ends_with? ".sqlpromptsnippet"
       doc = Document.new content_s
       title = XPath.first(doc, "//CodeSnippets/CodeSnippet/Header/Title").text
       snippet_text = XPath.first(doc, "//CodeSnippets/CodeSnippet/Snippet/Code").text
       post = Post.new(title: title, content: snippet_text, user: user, snippet_upload: snippet_upload)
       post.save
    else
       post = Post.new(title: snippet_upload.title, content: content_s, user: user, snippet_upload: snippet_upload)
       post.save
    end 
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet_upload
      @snippet_upload = SnippetUpload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_upload_params
      params.require(:snippet_upload).permit(:title, files:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/snippet_uploads_helper.rb
module SnippetUploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snippet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>


    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>

    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :snippet_upload_id %>
    <%= form.text_field :snippet_upload_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>Snippet upload</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user_id %></td>
        <td><%= post.snippet_upload_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

<%= link_to 'Xml to text', controller: 'posts' ,action: 'search', method: :get %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Snippet upload:</strong>
  <%= @post.snippet_upload_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/snippet_uploads/_form.html.erb
<%= form_with(model: snippet_upload, local: true) do |form| %>
  <% if snippet_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(snippet_upload.errors.count, "error") %> prohibited this snippet_upload from being saved:</h2>

      <ul>
        <% snippet_upload.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :files %>
    <%= form.file_field :files, multiple:true, accept: '.sql,.sqlpromptsnippet, text/plain' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/snippet_uploads/edit.html.erb
<h1>Editing Snippet Upload</h1>

<%= render 'form', snippet_upload: @snippet_upload %>

<%= link_to 'Show', @snippet_upload %> |
<%= link_to 'Back', snippet_uploads_path %>

app/views/snippet_uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Snippet Uploads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snippet_uploads.each do |snippet_upload| %>
      <tr>
        <td><%= snippet_upload.title %></td>
        <% if snippet_upload.user !=nil %> 
          <td><%= snippet_upload.user.email %></td>
        <% else %>
          <td> none </td>
        <% end %>
        <td><%= link_to 'Show', snippet_upload %></td>
        <td><%= link_to 'Edit', edit_snippet_upload_path(snippet_upload) %></td>
        <td><%= link_to 'Destroy', snippet_upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snippet Upload', new_snippet_upload_path %>

app/views/snippet_uploads/new.html.erb
<h1>New Snippet Upload</h1>

<%= render 'form', snippet_upload: @snippet_upload %>

<%= link_to 'Back', snippet_uploads_path %>

app/views/snippet_uploads/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @snippet_upload.title %>
  <%if @snippet_upload.user!=nil %>
	  <strong>User:</strong>
	  <%= @snippet_upload.user.email %>
  <%end%>
</p>


 
<% @snippet_upload.files.each do |file| %>
	<%= link_to file.filename, url_for(file) %>
	<br>
<% end %>


 

<%= link_to 'Edit', edit_snippet_upload_path(@snippet_upload) %> |
<%= link_to 'Back', snippet_uploads_path %>